### ISSUE TITLE
Change predict() generation for non-HMC algorithm to incorporate specified link function

### ISSUE THREAD

**Issue by alizma** [WardBrian/scikit-stan#3]
Though it is planned to generalize generate_quantities so that the method does not require an MCMC sample in a near-future Stan release, this package's predict() should generate quantities, with reference to the specified link function, from Python's provided distributions. 

The method also doesn't default correctly with discrete families at time of writing this issue...

**Comment by WardBrian** [comment]
This will be available in Cmdstan 2.31 (see https://github.com/stan-dev/cmdstan/pull/1106) so I’d call it pretty low priority
