### ISSUE TITLE
Add an example of using GLM object in a Pipeline or Grid Search

### ISSUE THREAD

**Issue by WardBrian** [WardBrian/scikit-stan#7]

**Comment by alizma** [comment]
There is now an example of a ``Pipeline`` alongside ``PolynomialFeatures()`` and ``StandardScaler()`` as a recreation of [this](https://scikit-learn.org/stable/auto_examples/linear_model/plot_ard.html) sklearn example, which is contained in the "Comparing Linear Bayesian Regressors" notebook. More to come, but this should suffice as a preliminary closing for this issue.
